#!/bin/bash

echo "Word counts of all <article> content:"
echo =============
echo

pwd

for dir in build/*/*/
do
  echo Checking $dir
  find $dir -name '*.html' -exec scripts/hwc {} ';'
  find $dir -name '*.html'
  perl -e 'print "hello\n"'

  WC=$(
    find $dir \
      -name '*.html' \
      -exec scripts/hwc {} ';' \
      | perl -ne '$SUM += $_; END { print "$SUM\n" }' )

  if [[ -n "$WC" && "$WC" -gt 0 ]]; then
    echo $dir
    echo $WC
  fi  
done


echo

