name: Vale + LLM Review

on:
  workflow_call:

env:
  TESTING_HAKIM: ${{ secrets.TESTING_HAKIM }}

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: install vale
        run: |
          if [ "$TESTING_HAKIM" == "docs-runner" ]; then
            echo "FOUND SECRET FROM docs-runner"
          elif [ "$TESTING_HAKIM" == "docs-tooling" ]; then
            echo "FOUND SECRET FROM docs-tooling"
          else
            echo "NO SECRET FOUND"
          fi


