name: Test secrets

on:
  workflow_call:

env:
  TESTING_HAKIM: ${{ secrets.TESTING_HAKIM }}

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: test secret
        run: |
          if [ "$TESTING_HAKIM" == "docs-runner" ]; then
            echo "FOUND SECRET 1 FROM runner"
          elif [ "$TESTING_HAKIM" == "docs-tooling" ]; then
            echo "FOUND SECRET 2 FROM tooling"
          else
            echo "NO SECRET FOUND - $TESTING_HAKIM"
          fi


