name: Vale + LLM Review

on:
  workflow_call:

jobs:
  run-vale:
    runs-on: ubuntu-latest

    steps:
      - name: install vale
        run: |
          sudo snap install vale

      - name: fetch runner config
        uses: actions/checkout@v4
        with:
          repository: couchbaselabs/docs-runner
          path: docs-runner

      - name: fetch styles
        uses: actions/checkout@v4
        with:
          repository: couchbaselabs/docs-style-guide
          sparse-checkout: ValeStyles/
          path: docs-style-guide

      - name: debug
        run: |
          sudo snap install tree
          tree .
