name: Vale + LLM Review

on:
  workflow_call:
    inputs:
      path:
        type: string
        default: ""

jobs:
  run-vale:
    runs-on: ubuntu-latest

    steps:
      - name: install vale
        run: |
          sudo snap install vale

      - name: fetch runner config
        uses: actions/checkout@v4
        with:
          repository: couchbaselabs/docs-runner
          path: docs-runner

      - name: fetch styles
        uses: actions/checkout@v4
        with:
          repository: couchbaselabs/docs-style-guide
          sparse-checkout: ValeStyles/
          path: docs-style-guide

      - name: debug
        run: |
          sudo snap install tree
          tree .

      - name: run vale
        run: |
          vale --config=docs-runner/.vale.ini --minAlertLevel=warning --output=JSON ${{ inputs.path }} > vale.json
          cat vale.json
          echo "Vale output saved to vale.json"
          echo "Vale output saved to vale.json" >> $GITHUB_ENV
