name: Vale + LLM Review

on:
  workflow_call:
    inputs:
      repository:
        description: "The repository to check out"
        required: true
        type: string
      path:
        type: string
        description: "The startPath pointing to the folder containing antora.yml"
        required: false
        default: "."
      pull_request_number:
        type: string
        description: "The pull request number to check out"
        required: true
      base_sha:
        type: string
        description: "The base sha to diff against"
        required: true
      head_sha:
        type: string
        description: "The head sha to comment against"
        required: true

jobs:
  run-vale:
    runs-on: ubuntu-latest

    steps:
      - name: check sha
        run: |
          echo $OPENAI_API_KEY | cksum
          echo $#OPENAI_API_KEY
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: install asciidoctor
        run: |
          sudo apt-get install -y asciidoctor

      - name: install vale
        run: |
          sudo snap install vale

      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.head_sha }}
          fetch-depth: 100 # or 0 for no limit?
          path: content-repo

      - name: fetch runner config
        uses: actions/checkout@v4
        with:
          repository: couchbaselabs/docs-runner
          path: docs-runner

      - name: fetch styles
        uses: actions/checkout@v4
        with:
          repository: couchbaselabs/docs-style-guide
          sparse-checkout: ValeStyles/
          path: docs-style-guide

      - name: debug
        run: |
          sudo snap install tree
          tree -a .

      - name: run vale
        working-directory: ./content-repo
        run: |
          CHANGED=$(git diff --name-only $BASE_SHA $CONTENT_PATH | xargs)
          echo $CHANGED
          vale --config=../docs-runner/.vale.ini \
            --minAlertLevel=warning \
            --output=JSON \
            --no-exit \
            $CHANGED > ../docs-runner/vale.json
          cat ../docs-runner/vale.json
        env:
          CONTENT_PATH: ${{ inputs.path }}
          BASE_SHA: ${{ inputs.base_sha }}

      - name: run git diff
        working-directory: ./content-repo
        run: |
          git diff $BASE_SHA $CONTENT_PATH > ../docs-runner/diff.txt
        env:
          CONTENT_PATH: ${{ inputs.path }}
          BASE_SHA: ${{ inputs.base_sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22 # minimum needed for Object.groupBy

      - name: run review.js
        working-directory: ./docs-runner
        run: |
          npm install
          node review.js
        env:
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
          REPOSITORY: ${{ inputs.repository }}
          HEAD_SHA: ${{ inputs.head_sha }}
          PULL_REQUEST_NUMBER: ${{ inputs.pull_request_number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}