name: Vale + LLM Review

on:
  workflow_dispatch

jobs:
  run-vale:
    runs-on: ubuntu-latest

    steps:
      - name: install vale
        run: |
          sudo snap install vale

      - name: fetch styles
        uses: actions/checkout@v4
        with:
          repository: couchbaselabs/docs-style-guide
          sparse-checkout: /ValeStyles/*

      - name: debug
        run: |
          sudo snap install tree
          tree .
